{% set name = "oop-ext" %}
{% set version = "0.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6646b1ee8d677789346fc1c6b74b17cda43248b5c4cb0e86cb2af95ad46d7617

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm    
  run:
    - python >=3.6

test:
  imports:
    - oop_ext
    - oop_ext.foundation
    - oop_ext.interface
  requires:
    - pytest
    - pytest-mock
  commands:
    - pytest --pyargs oop_ext

about:
  home: https://github.com/ESSS/oop-ext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: OOP Extensions is a set of utilities for object oriented programming which is missing on Python core libraries.
  doc_url: https://oop-ext.readthedocs.io/
  dev_url: https://github.com/ESSS/oop-ext

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
