travis:
  secure:
    BINSTAR_TOKEN: DEF8WR/17SYs8NM3KLTjGlVpICJaWD72RjtOOJy2YbfqT2HWarDE6ogBbpNVVUMpqQsnw4TuEBlUkx6PzGLZylmrLDOD2lqRoL+Q1I/8BIFqBbSkGzA7rq6ahZgY2VExQqoTc2b3NjRQQ2uveavsG2qmKkrXZPC1hYwZbfSkAsHfwBBbCRGkMCAoOLVbhTTBYZj9BtgA0BQaCKK+oyuUqinrO9W4skpqJEzFgf/Lo0HWDthNRalkSWp/QejUXEdkUBmZ8okscNoMUUoX44gT9l57KxhJZ2DjRxeSnYy6Yi1zN0LWS99OT6kAjyspuPtysEcqPC7Dru4y2ZWt9S68tIynKU4tGvXUNwAlNnVlnFpKObJPQK7MCoLyPfD4CgxkBvAxhO9i6sJ2vVYJIKLBawSpSx3p1a+8Q89Gw+NMP4y7+uxRWjsbuMtpU+iLzkxYr/PGoMXwLPoVPjY+lD/IEPBUCgnIhCyML3JU/ZXdt1IE8L9orxrfJO+mWafnfOhyivTMgvCuTm2sQ5zkptG9ENcB0IYFvJ2zMD+qTOhjy2sTGXJRimz5buHW1KgxHlFM2ohJzjOIe2x1Qb5m8/5cuybzMEKPYHDn+BShIprt4asDxP2e4XWIWDGkfDGBzv71IStEVxzc1AzaZ8xJ+u5+ZHPq1F8jf75mRFJ0S3Bdkpg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
